augmentation:
  document:
    fold_lines: false
    ink_bleed: true
    paper_texture: true
    shadow: true
  enabled: true
  geometric:
    elastic_transform:
      alpha: 50
      sigma: 5
    rotation_range:
    - -7
    - 7
    scale_range:
    - 0.92
    - 1.08
    shear_range:
    - -6
    - 6
    translate_percent: 0.08
  noise_blur:
    gaussian_blur_sigma:
    - 0
    - 1.8
    gaussian_noise_var:
    - 0
    - 0.015
    motion_blur_kernel:
    - 3
    - 7
  photometric:
    brightness_range:
    - 0.75
    - 1.25
    contrast_range:
    - 0.75
    - 1.25
    gamma_range:
    - 0.85
    - 1.15
    hue_range:
    - -0.05
    - 0.05
    saturation_range:
    - 0.9
    - 1.1
  probability: 0.85
dataset_generation:
  background_color:
  - 255
  - 255
  - 255
  char_spacing_range:
  - 0
  - 5
  character_set: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.,!?;:''-() '
  font_size_range:
  - 32
  - 56
  image_size:
  - 512
  - 512
  include_background_class: true
  line_spacing_range:
  - 1.2
  - 1.8
  margin:
  - 80
  - 80
  mask_dilation_kernel: 3
  mask_method: bounding_box
  max_chars_per_image: 120
  max_lines_per_image: 10
  min_chars_per_image: 30
  num_samples: 10000
  template_matching_threshold: 0.7
  test_split: 0.1
  text_alignment: left
  text_color_range:
  - - 0
    - 0
    - 0
  - - 50
    - 50
    - 50
  train_split: 0.8
  val_split: 0.1
hardware:
  device: cuda
  distributed: true
  gpu_ids:
  - 0
  - 1
  - 2
  - 3
  precision: 32
inference:
  batch_size: 2
  confidence_threshold: 0.5
  min_char_size: 10
  nms_threshold: 0.5
  tta: false
logging:
  checkpoint:
    mode: max
    monitor: val_iou_epoch
    save_last: true
    save_top_k: 3
  local:
    log_level: INFO
    save_frequency: 1
  wandb:
    enabled: true
    entity: null
    log_frequency: 100
    log_images: true
    log_model: true
    num_images_to_log: 8
    project: handwritten-char-segmentation
model:
  architecture: unet
  unet:
    activation: relu
    decoder_channels:
    - 512
    - 256
    - 128
    - 64
    dropout_rate: 0.25
    encoder_channels:
    - 64
    - 128
    - 256
    - 512
    - 1024
    encoder_depth: 5
    num_classes: 64
    use_batch_norm: true
    use_dropout: true
paths:
  checkpoints_dir: outputs/checkpoints
  fonts_dir: fonts
  images_dir: outputs/synthetic_data/images
  logs_dir: outputs/logs
  masks_dir: outputs/synthetic_data/masks
  metadata_dir: outputs/synthetic_data/metadata
  output_dir: outputs
  predictions_dir: outputs/predictions
  synthetic_data_dir: outputs/synthetic_data
project:
  description: Instance-level segmentation of handwritten characters using synthetic
    data
  name: handwritten_char_segmentation
  seed: 42
  version: 1.0.0
text_corpus:
  custom_text_file: null
  max_sentence_length: 20
  min_sentence_length: 5
  source: wikipedia
  wikipedia_articles: 150
  wikipedia_language: en
training:
  batch_size: 2
  early_stopping:
    enabled: true
    min_delta: 0.0005
    mode: max
    monitor: val_iou_epoch
    patience: 20
  gradient_clip_val: 1.0
  loss:
    ce_weight: 0.5
    class_weights: null
    dice_weight: 0.5
    focal_alpha: 0.75
    focal_gamma: 2.5
    name: dice
  num_epochs: 100
  num_workers: 2
  optimizer:
    betas:
    - 0.9
    - 0.999
    learning_rate: 0.001
    momentum: 0.9
    name: adamw
    weight_decay: 0.0001
  pin_memory: true
  scheduler:
    gamma: 0.1
    min_lr: 1.0e-07
    name: cosine
    patience: 10
    step_size: 30
  use_amp: false
validation:
  check_val_every_n_epoch: 1
  metrics:
  - iou
  - dice
  - pixel_accuracy
  - precision
  - recall
  - f1
  val_batch_size: 4
